logging:
  level:
    org.springframework:
      data: info
      security: INFO
server:
  port: 80
spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
useJwtTokenStore: false