logging:
  level:
    org.springframework:
      data: info
      security: info
server:
  port: 80
spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
useJwtTokenStore: false
spring-oauth-authorize: http://localhost/oauth/authorize
spring-oauth-token: http://localhost/oauth/token