spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-oauth2-redis
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
  redis:
    database: 1
    host: 10.1.51.96
    port: 6379
    password: redis
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
